version: "3.9"

services:
  frontend:
    container_name: newtech
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5180:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
